In [ ]:
#!pip install pdfminer
#!pip install PyPDF2
#!pip install pdfplumber

In [4]:
import pandas as pd
import os
import json
import numpy as np
from pdfminer.high_level import extract_text
from PyPDF2 import PdfReader
import pdfplumber

### Manipulação do relatório CSV

In [ ]:
relatorio = pd.read_csv(r"C:\Users\Usuario\Desktop\Repositorios_Bitbucket\crawer-ri-gpa\relatorios_consolidados.csv")
df_csv = pd.DataFrame(relatorio)

In [ ]:
df_filtrado = df_csv[~df_csv["empresa"].str.contains("MAGALU", case=False, na=False)]

In [10]:
# Caminho da pasta com os JSONs da Magalu
caminho_json_magalu = r"C:\Users\Usuario\Desktop\Repositorios_Bitbucket\crawer-ri-gpa\pdfs\Magalu"

# Lista para armazenar os dados
dados_json_magalu = []

# Percorre os arquivos da pasta
for raiz, _, arquivos in os.walk(caminho_json_magalu):
    if 'jsons' in raiz.lower():
        for nome_arquivo in arquivos:
            if nome_arquivo.endswith(".json"):
                caminho_json = os.path.join(raiz, nome_arquivo)
                try:
                    with open(caminho_json, "r", encoding="utf-8") as f:
                        dados = json.load(f)

                    dados_json_magalu.append({
                        "empresa": dados.get("empresa", "Desconhecida"),
                        "categoria": dados.get("categoria", ""),
                        "ano": dados.get("ano", ""),
                        "trimestre": dados.get("trimestre", ""),
                        "url": dados.get("download_url", ""),
                        "arquivo": nome_arquivo,
                        "paginas": dados.get("num_pages", ""),
                        "data_extracao": dados.get("data_extracao", ""),
                        "checksum": dados.get("checksum", "")
                    })
                except Exception as e:
                    print(f"Erro ao processar {caminho_json}: {e}")

# Cria DataFrame com os dados extraídos
df_json_magalu = pd.DataFrame(dados_json_magalu)

# Garante que todas as colunas estejam presentes
colunas_esperadas = ["empresa", "categoria", "ano", "trimestre", "url", "arquivo", "paginas", "data_extracao", "checksum"]
for col in colunas_esperadas:
    if col not in df_json_magalu.columns:
        df_json_magalu[col] = ""

df_json_magalu = df_json_magalu[colunas_esperadas]

# Carrega o CSV existente (se houver)
try:
    df_existente = pd.read_csv("relatorio_consolidado.csv")
except FileNotFoundError:
    df_existente = pd.DataFrame(columns=colunas_esperadas)

# Concatena os dados
df_final = pd.concat([df_existente, df_json_magalu], ignore_index=True)

# Salva o resultado atualizado
df_final.to_csv("relatorio_consolidado.csv", index=False)

print("Dados da Magalu adicionados com sucesso ao relatorio_consolidado.csv.")

Dados da Magalu adicionados com sucesso ao relatorio_consolidado.csv.

### Avaliação da raspagem

In [6]:
def verificar_relatorios_em_empresas(diretorio_base="pdfs"):
    print(f"\n Verificando relatórios na pasta base: {diretorio_base}\n")

    for empresa in os.listdir(diretorio_base):
        caminho_empresa = os.path.join(diretorio_base, empresa)
        if not os.path.isdir(caminho_empresa):
            continue

        print(f"\n Empresa: {empresa}")

        for pasta_ano in os.listdir(caminho_empresa):
            caminho_ano = os.path.join(caminho_empresa, pasta_ano)

            if os.path.isdir(caminho_ano):
                caminho_originais = os.path.join(caminho_ano, "originais")

                if os.path.exists(caminho_originais):
                    arquivos_pdf = [
                        f for f in os.listdir(caminho_originais)
                        if f.lower().endswith(".pdf")
                    ]
                    total = len(arquivos_pdf)

                    if total < 12:
                        print(f"{pasta_ano} - Apenas {total} relatórios encontrados (esperado: 12)")
                    else:
                        print(f"{pasta_ano} - OK ({total} relatórios)")
                else:
                    print(f"{pasta_ano} - Pasta 'originais' não encontrada")

verificar_relatorios_em_empresas("C:/Users/Usuario/Desktop/Repositorios_Bitbucket/crawer-ri-gpa/pdfs")

 Verificando relatórios na pasta base: C:/Users/Usuario/Desktop/Repositorios_Bitbucket/crawer-ri-gpa/pdfs


 Empresa: AmericanasSA
2020 - OK (13 relatórios)
2021 - OK (13 relatórios)
2022 - OK (12 relatórios)
2023 - OK (12 relatórios)
2024 - OK (12 relatórios)
2025 - Apenas 3 relatórios encontrados (esperado: 12)

 Empresa: CasasBahia
2021 - OK (12 relatórios)
2022 - OK (12 relatórios)
2023 - OK (12 relatórios)
2024 - OK (12 relatórios)
2025 - Apenas 3 relatórios encontrados (esperado: 12)

 Empresa: GPA
2020 - OK (12 relatórios)
2021 - OK (12 relatórios)
2022 - OK (12 relatórios)
2023 - OK (12 relatórios)
2024 - OK (12 relatórios)
2025 - Apenas 3 relatórios encontrados (esperado: 12)

 Empresa: MAGALU
2021 - OK (16 relatórios)
2022 - OK (16 relatórios)
2023 - OK (16 relatórios)
2024 - OK (16 relatórios)
2025 - Apenas 5 relatórios encontrados (esperado: 12)

 Empresa: PagueMenos
2020 - Apenas 10 relatórios encontrados (esperado: 12)
2021 - OK (12 relatórios)
2022 - OK (12 relatórios)
2023 - OK (12 relatórios)
2024 - OK (12 relatórios)
2025 - Apenas 3 relatórios encontrados (esperado: 12)

 Empresa: RaiaDrogasil
2020 - Apenas 0 relatórios encontrados (esperado: 12)
2021 - Apenas 0 relatórios encontrados (esperado: 12)
2022 - Apenas 0 relatórios encontrados (esperado: 12)
2023 - Apenas 0 relatórios encontrados (esperado: 12)
2024 - Apenas 0 relatórios encontrados (esperado: 12)
2025 - Apenas 0 relatórios encontrados (esperado: 12)

### Avaliação da Saida CSV

In [7]:
dados_csv = pd.read_csv(r"C:\Users\Usuario\Desktop\Repositorios_Bitbucket\crawer-ri-gpa\relatorios_consolidados.csv")
df_csv = pd.DataFrame(dados_csv)

In [8]:
df_csv.head()

,empresa,categoria,ano,trimestre,url,arquivo,paginas,data_extracao,checksum
0,MAGALU,Outros,2025,1T25,https://ri.magazineluiza.com.br/Download.aspx?...,pdfs\MAGALU\2025\originais\2025_1T25_RL.pdf,27,2025-05-21T16:16:08.952553+00:00,a67a7131a3e63cca0e77272ff8093b3d89adf84ed7a453...
1,MAGALU,Demonstrações Financeiras,2025,1T25,https://ri.magazineluiza.com.br/Download.aspx?...,pdfs\MAGALU\2025\originais\2025_1T25_ITR.pdf,57,2025-05-21T16:16:09.597321+00:00,d242627adaf34683d899dcf1f4a593a82df8bf7d4a07b3...
2,MAGALU,Apresentações,2025,1T25,https://ri.magazineluiza.com.br/Download.aspx?...,pdfs\MAGALU\2025\originais\2025_1T25_AP.pdf,24,2025-05-21T16:16:10.153871+00:00,ad0450985e0be0b36ecf2468ad0ad799405f1613568d1d...
3,MAGALU,Desconhecido,2025,1T25,https://ri.magazineluiza.com.br/Download.aspx?...,pdfs\MAGALU\2025\originais\2025_1T25_UNK.pdf,0,2025-05-21T16:16:39.243885+00:00,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...
4,MAGALU,Desconhecido,2025,1T25,https://ri.magazineluiza.com.br/Download.aspx?...,pdfs\MAGALU\2025\originais\2025_1T25_UNK.pdf,0,2025-05-21T16:16:39.754894+00:00,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...

In [9]:
#Zeros por coluna numerica
contagem_zeros = (df_csv == 0).sum()
print("Contagem de zeros por coluna numérica:", contagem_zeros)

Contagem de zeros por coluna numérica: empresa           0
categoria         0
ano               0
trimestre         0
url               0
arquivo           0
paginas          54
data_extracao     0
checksum          0
dtype: int64

In [10]:
# Filtra as linhas onde a coluna tem valor 0 ou está vazia
linhas_com_zeros_ou_vazias = df_csv[
    (df_csv['paginas'] == 0) | 
    (df_csv['paginas'].isna()) | 
    (df_csv['paginas'] == '')
]

# Exibe as linhas filtradas
linhas_com_zeros_ou_vazias.head()

,empresa,categoria,ano,trimestre,url,arquivo,paginas,data_extracao,checksum
3,MAGALU,Desconhecido,2025,1T25,https://ri.magazineluiza.com.br/Download.aspx?...,pdfs\MAGALU\2025\originais\2025_1T25_UNK.pdf,0,2025-05-21T16:16:39.243885+00:00,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...
4,MAGALU,Desconhecido,2025,1T25,https://ri.magazineluiza.com.br/Download.aspx?...,pdfs\MAGALU\2025\originais\2025_1T25_UNK.pdf,0,2025-05-21T16:16:39.754894+00:00,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...
5,MAGALU,Desconhecido,2025,1T25,https://ri.magazineluiza.com.br/ShowResultado....,pdfs\MAGALU\2025\originais\2025_1T25_UNK.pdf,0,2025-05-21T16:16:39.897145+00:00,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...
6,MAGALU,Desconhecido,2025,NaN,https://ri.magazineluiza.com.br/javascript:voi...,pdfs\MAGALU\2025\originais\2025__UNK.pdf,0,2025-05-21T16:16:40.136581+00:00,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...
7,MAGALU,Desconhecido,2025,NaN,https://ri.magazineluiza.com.br/javascript:voi...,pdfs\MAGALU\2025\originais\2025__UNK.pdf,0,2025-05-21T16:16:40.369217+00:00,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...

In [11]:
#Zeros por coluna tipo string
vazios_str = (df_csv == "").sum()
print("Contagem de valores vazios em formato str", vazios_str)

Contagem de valores vazios em formato str empresa          0
categoria        0
ano              0
trimestre        0
url              0
arquivo          0
paginas          0
data_extracao    0
checksum         0
dtype: int64

### Avaliação da saida de texto no JSON

In [ ]:
import os
import json
import numpy as np


def verificar_jsons_e_raw_text_em_empresas_problemas_apenas(diretorio_base="pdfs"):
    """
    Verifica arquivos JSON e o status de 'raw_text' dentro das estruturas
    de pastas de empresas e anos, retornando apenas informações sobre
    empresas/anos que possuem problemas.

    Problemas incluem:
    - Pasta 'jsons' não encontrada.
    - Nenhum arquivo JSON encontrado na pasta 'jsons'.
    - Arquivos JSON com 'raw_text' vazio ou ausente.
    - Arquivos JSON com 'raw_text' com menos de 100 caracteres.
    - Erros de leitura/parsing de arquivos JSON.

    Args:
        diretorio_base (str): O caminho para a pasta base que contém as pastas
                              das empresas (ex: 'pdfs').
    """
    print(f"\n--- Verificando arquivos JSON e 'raw_text' na pasta base: {diretorio_base} (Apenas Problemas) ---\n")

    # Percorre as pastas de cada empresa dentro do diretório base
    for nome_empresa in os.listdir(diretorio_base):
        caminho_empresa = os.path.join(diretorio_base, nome_empresa)

        # Pula se não for um diretório (ex: arquivos no nível raiz)
        if not os.path.isdir(caminho_empresa):
            continue

        # Lista para armazenar as mensagens de problemas de cada ano da empresa atual
        mensagens_problemas_empresa = []

        # Percorre as pastas de cada ano dentro da pasta da empresa
        for nome_pasta_ano in os.listdir(caminho_empresa):
            caminho_ano = os.path.join(caminho_empresa, nome_pasta_ano)

            # Pula se não for um diretório (ex: arquivos no nível da empresa)
            if not os.path.isdir(caminho_ano):
                continue

            # Flag para indicar se o ano atual tem algum problema
            ano_tem_problema = False
            # Lista temporária para as mensagens deste ano
            mensagens_ano_atual = []

            caminho_jsons = os.path.join(caminho_ano, "jsons")

            if os.path.exists(caminho_jsons) and os.path.isdir(caminho_jsons):
                arquivos_json = [f for f in os.listdir(caminho_jsons) if f.lower().endswith(".json")]
                total_jsons = len(arquivos_json)

                count_raw_text_valido = 0       # raw_text existe e tem >= 100 caracteres
                count_raw_text_vazio_ausente = 0 # raw_text é nulo, vazio ou só espaços
                count_raw_text_curto = 0         # raw_text existe, mas tem < 100 caracteres
                count_erros_leitura = 0

                if total_jsons > 0:
                    for nome_arquivo_json in arquivos_json:
                        caminho_completo_json = os.path.join(caminho_jsons, nome_arquivo_json)
                        try:
                            with open(caminho_completo_json, "r", encoding="utf-8") as f:
                                dados_json = json.load(f)

                            raw_text = dados_json.get("raw_text")

                            if not raw_text or not str(raw_text).strip():
                                count_raw_text_vazio_ausente += 1
                            else:
                                # Se não está vazio/ausente, verifica o comprimento
                                if len(raw_text) < 100:
                                    count_raw_text_curto += 1
                                else:
                                    count_raw_text_valido += 1
                        except Exception as e:
                            count_erros_leitura += 1
                            # Opcional: print(f"    [ERRO DETALHADO] {caminho_completo_json}: {e}")

                    # Verifica se houve *qualquer* problema para este ano
                    if count_raw_text_vazio_ausente > 0 or \
                       count_raw_text_curto > 0 or \
                       count_erros_leitura > 0:
                        ano_tem_problema = True
                        mensagens_ano_atual.append(f"  Ano {nome_pasta_ano}: {total_jsons} JSONs encontrados.")
                        # Sempre mostra o total válido, mesmo que seja 0, para contexto
                        mensagens_ano_atual.append(f"    - {count_raw_text_valido} com 'raw_text' válido (>= 100 chars).")
                        if count_raw_text_vazio_ausente > 0:
                            mensagens_ano_atual.append(f"    - **{count_raw_text_vazio_ausente}** com 'raw_text' vazio ou ausente.")
                        if count_raw_text_curto > 0:
                            mensagens_ano_atual.append(f"    - **{count_raw_text_curto}** com 'raw_text' muito curto (< 100 chars).")
                        if count_erros_leitura > 0:
                            mensagens_ano_atual.append(f"    - **{count_erros_leitura}** com erros de leitura/parsing.")
                else: # total_jsons == 0 (nenhum JSON encontrado na pasta 'jsons')
                    ano_tem_problema = True
                    mensagens_ano_atual.append(f"  Ano {nome_pasta_ano}: NENHUM JSON encontrado na pasta 'jsons'.")
            else: # Pasta 'jsons' não encontrada
                ano_tem_problema = True
                mensagens_ano_atual.append(f"  Ano {nome_pasta_ano}: Pasta 'jsons' **não encontrada** ou não é um diretório.")

            # Se este ano teve algum problema, adiciona suas mensagens à lista da empresa
            if ano_tem_problema:
                mensagens_problemas_empresa.extend(mensagens_ano_atual)

        # Após verificar todos os anos de uma empresa, se houver mensagens de problema, imprima
        if mensagens_problemas_empresa:
            print(f"\n### Empresa: {nome_empresa} (Problemas Encontrados) ###")
            for msg in mensagens_problemas_empresa:
                print(msg)

caminho_base_pdfs = r"C:\Users\Usuario\Desktop\Repositorios_Bitbucket\crawer-ri-gpa\pdfs"

verificar_jsons_e_raw_text_em_empresas_problemas_apenas(caminho_base_pdfs)

--- Verificando arquivos JSON e 'raw_text' na pasta base: C:\Users\Usuario\Desktop\Repositorios_Bitbucket\crawer-ri-gpa\pdfs (Apenas Problemas) ---


### Empresa: MAGALU (Problemas Encontrados) ###
  Ano 2021: 16 JSONs encontrados.
    - 12 com 'raw_text' válido (>= 100 chars).
    - **4** com 'raw_text' vazio ou ausente.
  Ano 2022: 16 JSONs encontrados.
    - 12 com 'raw_text' válido (>= 100 chars).
    - **4** com 'raw_text' vazio ou ausente.
  Ano 2023: 16 JSONs encontrados.
    - 12 com 'raw_text' válido (>= 100 chars).
    - **4** com 'raw_text' vazio ou ausente.
  Ano 2024: 16 JSONs encontrados.
    - 12 com 'raw_text' válido (>= 100 chars).
    - **4** com 'raw_text' vazio ou ausente.
  Ano 2025: 5 JSONs encontrados.
    - 3 com 'raw_text' válido (>= 100 chars).
    - **2** com 'raw_text' vazio ou ausente.

### Empresa: PagueMenos (Problemas Encontrados) ###
  Ano 2020: 10 JSONs encontrados.
    - 8 com 'raw_text' válido (>= 100 chars).
    - **2** com 'raw_text' muito curto (< 100 chars).

### Empresa: RaiaDrogasil (Problemas Encontrados) ###
  Ano 2020: NENHUM JSON encontrado na pasta 'jsons'.
  Ano 2021: NENHUM JSON encontrado na pasta 'jsons'.
  Ano 2022: NENHUM JSON encontrado na pasta 'jsons'.
  Ano 2023: NENHUM JSON encontrado na pasta 'jsons'.
  Ano 2024: NENHUM JSON encontrado na pasta 'jsons'.
  Ano 2025: NENHUM JSON encontrado na pasta 'jsons'.

### Avaliação da saida de txt

In [23]:
# Caminho da pasta onde estão as subpastas MAGALU, Casas Bahia, e GPA
caminho_base = r"C:\Users\Usuario\Desktop\Repositorios_Bitbucket\crawer-ri-gpa\pdfs"

# Lista para armazenar os dados
dados_txt = []

# Percorre todas as pastas e subpastas
for raiz, diretorios, arquivos in os.walk(caminho_base):
    # Verifica se está dentro da pasta 'textos' para processar os arquivos
    if 'textos' in raiz:
        for nome_arquivo in arquivos:
            if nome_arquivo.endswith(".txt"):
                caminho_completo = os.path.join(raiz, nome_arquivo)
                try:
                    # Abre o arquivo .txt e calcula o número total de caracteres
                    with open(caminho_completo, "r", encoding="utf-8") as f:
                        texto = f.read()

                    # Armazena o nome do arquivo e a soma dos caracteres
                    dados_txt.append([nome_arquivo, len(texto)])

                except Exception as e:
                    dados_txt.append([nome_arquivo, f"Erro: {e}"])

# Cria o DataFrame a partir da lista
df_txt = pd.DataFrame(dados_txt, columns=["Arquivo", "Total_caracteres"])

# Exibe o DataFrame
print(df_txt)

             Arquivo  Total_caracteres
0     2020_1T_AP.txt              4092
1    2020_1T_ITR.txt            175081
2     2020_1T_RR.txt             58604
3     2020_2T_AP.txt              5579
4    2020_2T_ITR.txt            180254
..               ...               ...
304  2024_4T_DFP.txt            214486
305   2024_4T_RR.txt             58060
306   2025_1T_AP.txt             14296
307  2025_1T_ITR.txt            156086
308   2025_1T_RR.txt             32511

[309 rows x 2 columns]

In [ ]:
vazios_str = df_txt[df_txt['Total_caracteres'] == 0]
print(vazios_str)

               Arquivo  Total_caracteres
182  2021_1T21_UNK.txt                 0
186  2021_2T21_UNK.txt                 0
190  2021_3T21_UNK.txt                 0
194  2021_4T21_UNK.txt                 0
198  2022_1T22_UNK.txt                 0
202  2022_2T22_UNK.txt                 0
206  2022_3T22_UNK.txt                 0
210  2022_4T22_UNK.txt                 0
214  2023_1T23_UNK.txt                 0
218  2023_2T23_UNK.txt                 0
222  2023_3T23_UNK.txt                 0
226  2023_4T23_UNK.txt                 0
230  2024_1T24_UNK.txt                 0
234  2024_2T24_UNK.txt                 0
238  2024_3T24_UNK.txt                 0
242  2024_4T24_UNK.txt                 0
246  2025_1T25_UNK.txt                 0
247      2025__UNK.txt                 0

### Avaliação dos arquivos individualmente

In [ ]:
def diagnosticar_pdf(caminho_pdf):
    print(f"\nAnalisando: {caminho_pdf}")

    # 1. Verifica número de páginas com PyPDF2
    try:
        reader = PdfReader(caminho_pdf)
        num_paginas = len(reader.pages)
        print(f"Número de páginas: {num_paginas}")
    except Exception as e:
        print(f"Erro ao ler número de páginas: {e}")
        return

    # 2. Extrai texto com pdfminer
    try:
        texto = extract_text(caminho_pdf)
        total_caracteres = len(texto.strip())
        print(f"Caracteres extraídos: {total_caracteres}")
    except Exception as e:
        print(f"Erro ao extrair texto: {e}")
        return

In [13]:
caminho_pdf = ""

In [14]:
def visualizar_pdf(path_pdf, preview_chars=500):
    print(f"\n Analisando: {path_pdf}")
    
    try:
        reader = PdfReader(caminho_pdf)
        num_paginas = len(reader.pages)
        print(f"Número de páginas: {num_paginas}")
        texto = extract_text(path_pdf)
        total = len(texto)
        print(f"Total de caracteres extraídos: {total}")

        if total == 0:
            print(" Texto vazio!")
            return
        
        # Visualização: primeiras e últimas partes
        print("\n INÍCIO DO TEXTO:")
        print(texto[:preview_chars])

        print("\n FIM DO TEXTO:")
        print(texto[-preview_chars:])

    except Exception as e:
        print(f"Erro ao extrair texto: {e}")

In [15]:
from pdfminer.high_level import extract_text

def extrair_com_pdfminer(caminho_pdf: str) -> str:
    """
    Extrai texto de um PDF usando pdfminer.
    Melhor para texto bruto, mas sem layout/table preservation.
    """
    try:
        texto = extract_text(caminho_pdf)
        return texto.strip()
    except Exception as e:
        print(f"[pdfminer] Erro ao extrair texto de {caminho_pdf}: {e}")
        return ""

In [16]:
import pdfplumber

def extrair_com_pdfplumber(caminho_pdf: str) -> str:
    """
    Extrai texto de um PDF usando pdfplumber.
    Preserva mais o layout e estrutura de colunas/tabelas.
    """
    texto = ""
    try:
        with pdfplumber.open(caminho_pdf) as pdf:
            for pagina in pdf.pages:
                pagina_texto = pagina.extract_text()
                if pagina_texto:
                    texto += pagina_texto + "\n"
        return texto.strip()
    except Exception as e:
        print(f"[pdfplumber] Erro ao extrair texto de {caminho_pdf}: {e}")
        return ""

In [19]:
caminho = r"C:\Users\Usuario\Desktop\Repositorios_Bitbucket\crawer-ri-gpa\pdfs\PagueMenos\2021\originais\2021_1T_ITR.pdf"

texto_pdfminer = extrair_com_pdfminer(caminho)
texto_pdfplumber = extrair_com_pdfplumber(caminho)

In [20]:
print(texto_pdfminer)

ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

Demonstração do Valor Adicionado10Comentário do Desempenho11DMPL - 01/01/2020 à 31/03/20209Declaração dos Diretores sobre o Relatório do Auditor Independente60DMPL - 01/01/2021 à 31/03/20218Relatório da Revisão Especial - Sem Ressalva57Declaração dos Diretores sobre as Demonstrações Financeiras58Notas Explicativas29Pareceres e DeclaraçõesDFs IndividuaisBalanço Patrimonial Ativo2Composição do Capital1Demonstração das Mutações do Patrimônio LíquidoDados da EmpresaDemonstração do Resultado Abrangente5Demonstração do Fluxo de Caixa6Balanço Patrimonial Passivo3Demonstração do Resultado4ÍndiceITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 1 de 61

Em TesourariaTotal443.781.062Preferenciais0Ordinárias1.040.000Total1.040.000Preferenciais0Do Capital IntegralizadoOrdinárias443.781.062Dados da Empresa / Composição do CapitalNúmero de Ações(cid:10)(Unidades)Trimestre Atual(cid:10)31/03/2021ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 2 de 61

1.02.01.03Aplicações Financeiras Avaliadas ao Custo Amortizado9.5479.5171.02.01Ativo Realizável a Longo Prazo593.027611.5271.02.01.07Tributos Diferidos189.036192.5551.02.01.10Outros Ativos Não Circulantes394.444409.4551.02.01.07.01Imposto de Renda e Contribuição Social Diferidos189.036192.5551.01.08Outros Ativos Circulantes3.9605.7881.01.06.01Tributos Correntes a Recuperar189.561198.3181.01.08.03Outros3.9605.7881.02Ativo Não Circulante2.556.5612.606.3881.01.08.03.01Operações com Derivativos3.9605.7881.02.03.01Imobilizado em Operação540.323541.2891.02.03Imobilizado540.323541.2891.02.04Intangível1.352.0431.382.7751.02.04.01.02Direito de Uso em Arrendamento1.313.7971.344.9101.02.04.01Intangíveis1.352.0431.382.7751.02.01.10.04Depósitos Judiciais39.94538.6451.02.01.10.03Impostos e Contribuições a Recuperar354.499370.8101.02.02Investimentos71.16870.7971.02.02.01.04Outros Investimentos71.16870.7971.02.02.01Participações Societárias71.16870.7971.02.04.01.03Intangíveis38.24637.8651.01.03Contas a Receber724.534621.2231.01.02.03Aplicações Financeiras Avaliadas ao Custo Amortizado030.8801.01.03.01.01Contas a Receber de Clientes - Cartões de Créditos571.376511.5161.01.03.01Clientes589.476522.9401.01.02Aplicações Financeiras030.8801Ativo Total5.751.9485.753.7781.01.06Tributos a Recuperar189.561198.3181.01.01Caixa e Equivalentes de Caixa478.230589.0861.01Ativo Circulante3.195.3873.147.3901.01.03.01.02Convenios a Receber21.1089.7311.01.03.02.02Despesas antecipadas21.5248.2021.01.03.02.01Acordos Comerciais81.45666.3461.01.04Estoques1.799.1021.702.0951.01.03.02.03Outras32.07823.7351.01.03.02Outras Contas a Receber135.05898.2831.01.03.01.04Programa de Beneficios de Medicamentos - PBM2.0376.2491.01.03.01.03Comissoes a Receber4752201.01.03.01.06Ajuste a Valor Presente-4.224-3.7831.01.03.01.05Provisão para Créditos de Liquidação Duvidosa-1.296-993DFs Individuais / Balanço Patrimonial Ativo (cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaTrimestre Atual(cid:13)(cid:10)31/03/2021Exercício Anterior 31/12/2020ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 3 de 61

2.02.02.02.04Impostos e Contribuições a recolher8.0898.2142.02.02.02Outros1.236.2921.259.6682.02.02.02.05Arrendamento Mercantil1.228.2031.251.4542.02.04.01Provisões Fiscais Previdenciárias Trabalhistas e Cíveis28.47427.2412.02.04Provisões28.47427.2412.02.02Outras Obrigações1.236.2921.259.6682.02.01Empréstimos e Financiamentos600.524636.8472.02Passivo Não Circulante1.865.2901.923.7562.02.01.01Empréstimos e Financiamentos407.473387.1752.02.01.02Debêntures193.051249.6722.02.01.01.01Em Moeda Nacional407.473387.1752.03.04Reservas de Lucros346.400356.8252.03.02Reservas de Capital386.166383.4322.03.04.01Reserva Legal39.64639.6462.03.04.09Ações em Tesouraria-10.42402.03.04.07Reserva de Incentivos Fiscais317.178317.1792.03.01Capital Social Realizado1.199.4701.200.6662.02.04.01.02Provisões Previdenciárias e Trabalhistas24.73123.2152.02.04.01.01Provisões Fiscais1463392.02.04.01.04Provisões Cíveis2.8632.8192.03Patrimônio Líquido1.976.2041.940.9232.02.04.01.05Provisões para Contingências7348682.03.05Lucros/Prejuízos Acumulados44.16802.01.02Fornecedores1.250.1311.244.4902.01.01.02.01Salários e Férias a Pagar112.26689.2342.01.02.01Fornecedores Nacionais1.250.1311.244.4902.01.03.01Obrigações Fiscais Federais28.37335.5692.01.03Obrigações Fiscais106.134106.3992Passivo Total5.751.9485.753.7782.01.05.02.10Arrendamento Mercantil173.149172.2802.01Passivo Circulante1.910.4541.889.0992.01.01.02Obrigações Trabalhistas112.26689.2342.01.01Obrigações Sociais e Trabalhistas112.26689.2342.01.03.02Obrigações Fiscais Estaduais70.71267.1742.01.05.02Outros209.205207.3472.01.05Outras Obrigações209.205207.3472.01.05.02.04Arrecadação de Recursos de Terceiros04.0022.01.05.02.09Aluguéis a Pagar18.57718.3592.01.05.02.05Outras Contas a Pagar17.47912.7062.01.04Empréstimos e Financiamentos232.718241.6292.01.03.03Obrigações Fiscais Municipais7.0493.6562.01.04.01Empréstimos e Financiamentos158.714206.8642.01.04.02Debêntures74.00434.7652.01.04.01.01Em Moeda Nacional158.714206.864DFs Individuais / Balanço Patrimonial Passivo (cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaTrimestre Atual(cid:13)(cid:10)31/03/2021Exercício Anterior 31/12/2020ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 4 de 61

3.07Resultado Antes dos Tributos sobre o Lucro48.562-5.9593.08Imposto de Renda e Contribuição Social sobre o Lucro-4.39415.1633.06.02Despesas Financeiras-68.324-147.3493.06Resultado Financeiro-46.887-68.9663.06.01Receitas Financeiras21.43778.3833.08.01Corrente-87503.99Lucro por Ação - (Reais / Ação)3.99.01Lucro Básico por Ação3.11Lucro/Prejuízo do Período44.1689.2043.08.02Diferido-3.51915.1633.09Resultado Líquido das Operações Continuadas44.1689.2043.99.01.02ON0,100000,020003.03Resultado Bruto569.013507.4863.04Despesas/Receitas Operacionais-473.564-444.4793.02Custo dos Bens e/ou Serviços Vendidos-1.207.307-1.156.4013.05Resultado Antes do Resultado Financeiro e dos Tributos95.44963.0073.01Receita de Venda de Bens e/ou Serviços1.776.3201.663.8873.04.05Outras Despesas Operacionais-275-3113.04.06Resultado de Equivalência Patrimonial371-5533.04.04Outras Receitas Operacionais3181.7313.04.01Despesas com Vendas-418.400-398.2213.04.02Despesas Gerais e Administrativas-55.578-47.125DFs Individuais / Demonstração do Resultado(cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaAcumulado do Atual Exercício 01/01/2021 à 31/03/2021Acumulado do Exercício Anterior(cid:13)(cid:10)01/01/2020 à 31/03/2020ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 5 de 61

4.01Lucro Líquido do Período44.1689.2044.03Resultado Abrangente do Período44.1689.204DFs Individuais / Demonstração do Resultado Abrangente(cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaAcumulado do Atual Exercício 01/01/2021 à 31/03/2021Acumulado do Exercício Anterior(cid:13)(cid:10)01/01/2020 à 31/03/2020ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 6 de 61

6.01.03.02Pagamento de empréstimos tomados - juros-10.203-5.7056.01.03Outros-40.942-41.6146.01.02.13Outras contas a pagar4.8498.3876.02Caixa Líquido Atividades de Investimento8.244-5.1726.01.03.05Pagamento de arrendamentos - juros-27.478-29.4916.01.03.03Pagamento de debêntures tomada - juros-3.261-6.4186.01.02.07Despesas antecipadas-13.322-10.1856.01.02.06Outros Créditos-24.7898.8046.01.02.05Impostos a Recuperar23.511-20.0576.01.02.11Salários e férias a pagar25.76610.0646.01.02.09Impostos e contribuições a recolher-1.265-3.7936.01.02.08Fornecedores5.39111.7056.03.07Liquidação dos swaps – efeito caixa02.9156.03.06Pagamento de debênture tomada - principal-16.66706.03.03Pagamento de Arrendamento Mercantil-32.666-29.6286.02.11Aquisição de intangível-3.010-8986.02.09Aquisição de ativo imobilizado-19.596-4.2646.02.05Aplicações financeiras30.850-106.03.02Pagamento de empréstimos tomados - Principal-182.781-28.1066.03.01Empréstimos tomados - Principal160.00006.03Caixa Líquido Atividades de Financiamento-83.734-54.3976.01.01.05Valor justo de instrumentos financeiros1.091-56.6236.01.01.04Juros sobre empréstimos, financiamentos e debêntures8.61411.0916.01.01.06Variação Cambial1.55260.0106.01.01.08Constituição (reversão) da Provisão para Contingências1.3741.9996.01.01.07Juros sobre Arrendamento Mercantil27.47829.4916.01.01.03Ajuste a valor presente nos ativos e passivos7001946.01Caixa Líquido Atividades Operacionais-35.36620.9476.01.02.04Estoques-93.970-29.5026.01.01Caixa Gerado nas Operações150.686107.3576.01.01.02Depreciação e Amortização63.89362.4056.01.01.01Lucro Líquido do Exercício44.1689.2046.01.01.09Resultado de equivalência patrimonial-3715536.01.01.20Provisão para perdas nos estoques-3.0464.1366.01.01.19Provisão para perdas de crédito de liquidação duvidosa1.8951.6676.01.02Variações nos Ativos e Passivos-145.110-44.7966.01.02.02Contas a Receber de Clientes-67.279-20.7466.01.02.01Arrecadação de recursos de terceiros-4.0025276.01.01.17Baixa líquida dos bens do ativo imobilizado e intangível1.7825106.01.01.11Imposto de Renda e Contribuição Social Diferidos3.519-15.1636.01.01.10Imposto de Renda e Contribuição Social Correntes87506.01.01.13Constituição (realização) das tarifas antecipadas - empréstimos, financiamentos e debêntures-1.7511566.01.01.16Provisão para encerramento de lojas-975-5726.01.01.14Outros ajustes ao lucro-112-1.701DFs Individuais / Demonstração do Fluxo de Caixa - Método Indireto(cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaAcumulado do Atual Exercício 01/01/2021 à 31/03/2021Acumulado do Exercício Anterior(cid:13)(cid:10)01/01/2020 à 31/03/2020ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 7 de 61

6.03.13Ações em tesouraria-10.42406.05Aumento (Redução) de Caixa e Equivalentes-110.856-38.6226.05.01Saldo Inicial de Caixa e Equivalentes589.086121.0406.05.02Saldo Final de Caixa e Equivalentes478.23082.4186.03.12Custos com Emissão de Ações-1.19606.03.09Recursos provenientes das opções de ações outorgadas0422DFs Individuais / Demonstração do Fluxo de Caixa - Método Indireto(cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaAcumulado do Atual Exercício 01/01/2021 à 31/03/2021Acumulado do Exercício Anterior(cid:13)(cid:10)01/01/2020 à 31/03/2020ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 8 de 61

5.05.01Lucro Líquido do Período00044.168044.1685.05Resultado Abrangente Total00044.168044.1685.06Mutações Internas do Patrimônio Líquido-1.1962.7340001.5385.06.09Plano de Ações Restritas02.7340002.7345.06.08Custos com Emissão de Ações-1.1960000-1.1965.07Saldos Finais1.199.470375.742356.82444.16801.976.2045.01Saldos Iniciais1.200.666383.432356.824001.940.9225.04.04Ações em Tesouraria Adquiridas0-10.424000-10.4245.04Transações de Capital com os Sócios0-10.424000-10.4245.03Saldos Iniciais Ajustados1.200.666383.432356.824001.940.922DFs Individuais / Demonstração das Mutações do Patrimônio Líquido / DMPL - 01/01/2021 à 31/03/2021(cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaCapital Social IntegralizadoReservas de Capital, Opções Outorgadas e Ações em TesourariaReservas de LucroLucros ou Prejuízos AcumuladosOutros Resultados AbrangentesPatrimônio LíquidoITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 9 de 61

5.05.01Lucro Líquido do Período0009.20409.2045.07Saldos Finais382.727381.423260.7929.20401.034.1465.06.04Opções Outorgadas Reconhecidas04220004225.06Mutações Internas do Patrimônio Líquido04220004225.05Resultado Abrangente Total0009.20409.2045.01Saldos Iniciais382.727381.001260.792001.024.5205.03Saldos Iniciais Ajustados382.727381.001260.792001.024.520DFs Individuais / Demonstração das Mutações do Patrimônio Líquido / DMPL - 01/01/2020 à 31/03/2020(cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaCapital Social IntegralizadoReservas de Capital, Opções Outorgadas e Ações em TesourariaReservas de LucroLucros ou Prejuízos AcumuladosOutros Resultados AbrangentesPatrimônio LíquidoITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 10 de 61

7.08.01.02Benefícios20.05521.4367.08.01.03F.G.T.S.13.32212.6237.08.02Impostos, Taxas e Contribuições238.116194.6477.08.01.01Remuneração Direta182.382173.7747.07Valor Adicionado Total a Distribuir544.144467.4307.08Distribuição do Valor Adicionado544.144467.4307.08.01Pessoal215.759207.8337.08.03.01Juros35.60347.9087.08.03.02Aluguéis10.4987.8387.08.04Remuneração de Capitais Próprios44.1689.2047.08.03Remuneração de Capitais de Terceiros46.10155.7467.08.02.01Federais45.59419.8937.08.02.02Estaduais187.939173.1517.08.02.03Municipais4.5831.6037.08.04.03Lucros Retidos / Prejuízo do Período44.1689.2047.01.02Outras Receitas3181.7317.02Insumos Adquiridos de Terceiros-1.292.671-1.225.8207.02.01Custos Prods., Mercs. e Servs. Vendidos-1.115.121-1.060.5067.06.02Receitas Financeiras11.9797.0627.01Receitas1.888.3581.749.1467.01.01Vendas de Mercadorias, Produtos e Serviços1.888.0401.747.4157.02.02Materiais, Energia, Servs. de Terceiros e Outros-177.550-165.3147.05Valor Adicionado Líquido Produzido531.794460.9217.06Vlr Adicionado Recebido em Transferência12.3506.5097.06.01Resultado de Equivalência Patrimonial371-5537.03Valor Adicionado Bruto595.687523.3267.04Retenções-63.893-62.4057.04.01Depreciação, Amortização e Exaustão-63.893-62.405DFs Individuais / Demonstração do Valor Adicionado (cid:13)(cid:10)(cid:13)(cid:10)(Reais Mil)Código da ContaDescrição da ContaAcumulado do Atual Exercício 01/01/2021 à 31/03/2021Acumulado do Exercício Anterior(cid:13)(cid:10)01/01/2020 à 31/03/2020ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 11 de 61

Comentário do DesempenhoFortaleza,Ceará,3demaiode2021.AEmpreendimentosPagueMenosS.A.(“Companhia”ou“PagueMenos”),desde2009únicarededovarejofarmacêuticobrasileiropresenteemtodososestadosdoBrasil,levandosaúdeamaisde300municípiosbrasileiros,anunciaseusresultadosreferentesao1°trimestrede2021.AsinformaçõesfinanceirasforampreparadasdeacordocomasNormasInternacionaisdeRelatóriosFinanceiros(IFRS),deacordocomaspráticascontábeisadotadasnoBrasil(BRGAAP)eforamrevisadaspelosauditoresindependentesdeacordocomasnormasbrasileiraseinternacionaisdeauditoria.Desde2019,nossasdemonstraçõesfinanceirassãopreparadasdeacordocomoIFRS16,quealterouoscritériosdereconhecimentodoscontratosdealuguel.Parademonstrarosefeitosdaimplementaçãodestanormaefacilitaracomparabilidadeentreperíodos,apresentamosnapágina15destereleaseoDemonstrativodoResultadodoExercícioexcluindoosefeitosdoIFRS16.PRINCIPAISDESTAQUES1T21Venda Mesmas Lojas: crescimento de 9,6% (8,7% em lojas maduras)Venda Média Loja Mensal: R$ 578 mil, crescimento de 10,6%Digital: crescimento de 140%, representando 6,1% das vendas totais (+3,4p.p. vs1T20)ClinicFarma: crescimento de 180% no faturamento, com adesão de 6,2% da base total de clientesEBITDA : R$ 159,3 milhões (+27,1% vs1T20), com margem EBITDA de 8,3% (+1,2p.p. vs1T20).Lucro Líquido :R$ 44,2 milhões (+380% vs1T20), com margem líquida de 2,3% (+1,8p.p. vs1T20)Mercado de Capitais: Valorização acumulada da ação desde o IPO de 12,9%1T21DESTAQUES FINANCEIROS (R$ milhões)1T201T21ΔReceita Bruta1.763,2 1.910,2 8,3% Lucro Bruto507,5 569,0 12,1% % Margem Bruta28,8%29,8%1,0 p.p. Despesas com Vendas, Adm. e Gerais(382,1)(409,7)7,2% % Despesas (21,7%)(21,5%)0,2 p.p. EBITDA 125,4 159,3 27,1% % Margem EBITDA 7,1%8,3%1,2 p.p. Lucro (Prejuízo) Líquido 9,2 44,2 379,9% % Margem Líquida0,5% 2,3% 1,8 p.p. DESTAQUES OPERACIONAIS1T201T21Δ# de Lojas 1.124 1.101(2,0%)# de Lojas com Clinic Farma801 8232,7% Venda Média/loja/mês (R$ mil)523 578 10,6% # de Atendimentos (mil)29.536 26.067 (11,7%)Ticket Médio (R$) 59,70 73,28 22,8% # de Funcionários 19.900 19.121 (3,9%)# de Funcionários/loja17,7 17,4 (0,3)% de Vendas dos Canais Digitais2,7%6,1%3,4p.p. ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 12 de 61

Comentário do DesempenhoCE: 180RN: 43PB: 51PE: 117SE: 35BA: 114AL: 30PI: 35MA: 60AM: 22PA: 34RO: 13AC: 12RR: 9AP: 6TO: 15GO: 28DF: 17MG: 63ES: 26RJ: 19SP: 84MT: 23MS: 23PR: 15SC: 20RS: 78%17%13%58%4%100%PORTFÓLIODELOJASEncerramoso1T21com1.101lojasdistribuídasem325municípios,sendo88,5%delojasmaduras.Inauguramosemmarçode2021aprimeiralojadonovociclodeexpansão,ummêsantesdadataplanejada.Ocronogramadeaberturascontinuadentrodoprevisto,commaislojasinauguradasno2T21eritmodeaberturasnormalizadoduranteosegundosemestre.No1T21,foramfechadas5lojase7filiaisforamreformadas.1.1241.1121.1051.1051.1013T201T202T204T201T2175,7%78,5%80,8%85,6%88,5%12,9%12,8%13,4%10,6%9,7%9,6%7,6%2T201,8%1T201,1%3T200,8%5,0%0,4%3,4%4T200,1%1,7%1T213º Ano1º AnoMaduras2º AnoBase de LojasPerfil Etário de LojasDistribuição por UFAberturas de Lojas UDM*Fechamentos de Lojas UDM*NordesteSudesteNorteNordesteCentro-OesteSul* UDM: últimos doze mesesITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A.

Versão : 1

PÁGINA: 13 de 61


In [21]:
print(texto_pdfplumber)

ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
Índice
Dados da Empresa
Composição do Capital 1
DFs Individuais
Balanço Patrimonial Ativo 2
Balanço Patrimonial Passivo 3
Demonstração do Resultado 4
Demonstração do Resultado Abrangente 5
Demonstração do Fluxo de Caixa 6
Demonstração das Mutações do Patrimônio Líquido
DMPL - 01/01/2021 à 31/03/2021 8
DMPL - 01/01/2020 à 31/03/2020 9
Demonstração do Valor Adicionado 10
Comentário do Desempenho 11
Notas Explicativas 29
Pareceres e Declarações
Relatório da Revisão Especial - Sem Ressalva 57
Declaração dos Diretores sobre as Demonstrações Financeiras 58
Declaração dos Diretores sobre o Relatório do Auditor Independente 60
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
Dados da Empresa / Composição do Capital
Número de Ações(cid:10) Trimestre Atual(cid:10)
(Unidades) 31/03/2021
Do Capital Integralizado
Ordinárias 443.781.062
Preferenciais 0
Total 443.781.062
Em Tesouraria
Ordinárias 1.040.000
Preferenciais 0
Total 1.040.000
PÁGINA: 1 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Balanço Patrimonial Ativo (cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Trimestre Atual(cid:13)(cid:10) Exercício Anterior
Conta 31/03/2021 31/12/2020
1 Ativo Total 5.751.948 5.753.778
1.01 Ativo Circulante 3.195.387 3.147.390
1.01.01 Caixa e Equivalentes de Caixa 478.230 589.086
1.01.02 Aplicações Financeiras 0 30.880
1.01.02.03 Aplicações Financeiras Avaliadas ao Custo Amortizado 0 30.880
1.01.03 Contas a Receber 724.534 621.223
1.01.03.01 Clientes 589.476 522.940
1.01.03.01.01 Contas a Receber de Clientes - Cartões de Créditos 571.376 511.516
1.01.03.01.02 Convenios a Receber 21.108 9.731
1.01.03.01.03 Comissoes a Receber 475 220
1.01.03.01.04 Programa de Beneficios de Medicamentos - PBM 2.037 6.249
1.01.03.01.05 Provisão para Créditos de Liquidação Duvidosa -1.296 -993
1.01.03.01.06 Ajuste a Valor Presente -4.224 -3.783
1.01.03.02 Outras Contas a Receber 135.058 98.283
1.01.03.02.01 Acordos Comerciais 81.456 66.346
1.01.03.02.02 Despesas antecipadas 21.524 8.202
1.01.03.02.03 Outras 32.078 23.735
1.01.04 Estoques 1.799.102 1.702.095
1.01.06 Tributos a Recuperar 189.561 198.318
1.01.06.01 Tributos Correntes a Recuperar 189.561 198.318
1.01.08 Outros Ativos Circulantes 3.960 5.788
1.01.08.03 Outros 3.960 5.788
1.01.08.03.01 Operações com Derivativos 3.960 5.788
1.02 Ativo Não Circulante 2.556.561 2.606.388
1.02.01 Ativo Realizável a Longo Prazo 593.027 611.527
1.02.01.03 Aplicações Financeiras Avaliadas ao Custo Amortizado 9.547 9.517
1.02.01.07 Tributos Diferidos 189.036 192.555
1.02.01.07.01 Imposto de Renda e Contribuição Social Diferidos 189.036 192.555
1.02.01.10 Outros Ativos Não Circulantes 394.444 409.455
1.02.01.10.03 Impostos e Contribuições a Recuperar 354.499 370.810
1.02.01.10.04 Depósitos Judiciais 39.945 38.645
1.02.02 Investimentos 71.168 70.797
1.02.02.01 Participações Societárias 71.168 70.797
1.02.02.01.04 Outros Investimentos 71.168 70.797
1.02.03 Imobilizado 540.323 541.289
1.02.03.01 Imobilizado em Operação 540.323 541.289
1.02.04 Intangível 1.352.043 1.382.775
1.02.04.01 Intangíveis 1.352.043 1.382.775
1.02.04.01.02 Direito de Uso em Arrendamento 1.313.797 1.344.910
1.02.04.01.03 Intangíveis 38.246 37.865
PÁGINA: 2 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Balanço Patrimonial Passivo (cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Trimestre Atual(cid:13)(cid:10) Exercício Anterior
Conta 31/03/2021 31/12/2020
2 Passivo Total 5.751.948 5.753.778
2.01 Passivo Circulante 1.910.454 1.889.099
2.01.01 Obrigações Sociais e Trabalhistas 112.266 89.234
2.01.01.02 Obrigações Trabalhistas 112.266 89.234
2.01.01.02.01 Salários e Férias a Pagar 112.266 89.234
2.01.02 Fornecedores 1.250.131 1.244.490
2.01.02.01 Fornecedores Nacionais 1.250.131 1.244.490
2.01.03 Obrigações Fiscais 106.134 106.399
2.01.03.01 Obrigações Fiscais Federais 28.373 35.569
2.01.03.02 Obrigações Fiscais Estaduais 70.712 67.174
2.01.03.03 Obrigações Fiscais Municipais 7.049 3.656
2.01.04 Empréstimos e Financiamentos 232.718 241.629
2.01.04.01 Empréstimos e Financiamentos 158.714 206.864
2.01.04.01.01 Em Moeda Nacional 158.714 206.864
2.01.04.02 Debêntures 74.004 34.765
2.01.05 Outras Obrigações 209.205 207.347
2.01.05.02 Outros 209.205 207.347
2.01.05.02.04 Arrecadação de Recursos de Terceiros 0 4.002
2.01.05.02.05 Outras Contas a Pagar 17.479 12.706
2.01.05.02.09 Aluguéis a Pagar 18.577 18.359
2.01.05.02.10 Arrendamento Mercantil 173.149 172.280
2.02 Passivo Não Circulante 1.865.290 1.923.756
2.02.01 Empréstimos e Financiamentos 600.524 636.847
2.02.01.01 Empréstimos e Financiamentos 407.473 387.175
2.02.01.01.01 Em Moeda Nacional 407.473 387.175
2.02.01.02 Debêntures 193.051 249.672
2.02.02 Outras Obrigações 1.236.292 1.259.668
2.02.02.02 Outros 1.236.292 1.259.668
2.02.02.02.04 Impostos e Contribuições a recolher 8.089 8.214
2.02.02.02.05 Arrendamento Mercantil 1.228.203 1.251.454
2.02.04 Provisões 28.474 27.241
2.02.04.01 Provisões Fiscais Previdenciárias Trabalhistas e Cíveis 28.474 27.241
2.02.04.01.01 Provisões Fiscais 146 339
2.02.04.01.02 Provisões Previdenciárias e Trabalhistas 24.731 23.215
2.02.04.01.04 Provisões Cíveis 2.863 2.819
2.02.04.01.05 Provisões para Contingências 734 868
2.03 Patrimônio Líquido 1.976.204 1.940.923
2.03.01 Capital Social Realizado 1.199.470 1.200.666
2.03.02 Reservas de Capital 386.166 383.432
2.03.04 Reservas de Lucros 346.400 356.825
2.03.04.01 Reserva Legal 39.646 39.646
2.03.04.07 Reserva de Incentivos Fiscais 317.178 317.179
2.03.04.09 Ações em Tesouraria -10.424 0
2.03.05 Lucros/Prejuízos Acumulados 44.168 0
PÁGINA: 3 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Demonstração do Resultado(cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Acumulado do Atual Acumulado do Exercício
Conta Exercício 01/01/2021 à Anterior(cid:13)(cid:10)
31/03/2021 01/01/2020 à 31/03/2020
3.01 Receita de Venda de Bens e/ou Serviços 1.776.320 1.663.887
3.02 Custo dos Bens e/ou Serviços Vendidos -1.207.307 -1.156.401
3.03 Resultado Bruto 569.013 507.486
3.04 Despesas/Receitas Operacionais -473.564 -444.479
3.04.01 Despesas com Vendas -418.400 -398.221
3.04.02 Despesas Gerais e Administrativas -55.578 -47.125
3.04.04 Outras Receitas Operacionais 318 1.731
3.04.05 Outras Despesas Operacionais -275 -311
3.04.06 Resultado de Equivalência Patrimonial 371 -553
3.05 Resultado Antes do Resultado Financeiro e dos Tributos 95.449 63.007
3.06 Resultado Financeiro -46.887 -68.966
3.06.01 Receitas Financeiras 21.437 78.383
3.06.02 Despesas Financeiras -68.324 -147.349
3.07 Resultado Antes dos Tributos sobre o Lucro 48.562 -5.959
3.08 Imposto de Renda e Contribuição Social sobre o Lucro -4.394 15.163
3.08.01 Corrente -875 0
3.08.02 Diferido -3.519 15.163
3.09 Resultado Líquido das Operações Continuadas 44.168 9.204
3.11 Lucro/Prejuízo do Período 44.168 9.204
3.99 Lucro por Ação - (Reais / Ação)
3.99.01 Lucro Básico por Ação
3.99.01.02 ON 0,10000 0,02000
PÁGINA: 4 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Demonstração do Resultado Abrangente(cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Acumulado do Atual Acumulado do Exercício
Conta Exercício 01/01/2021 à Anterior(cid:13)(cid:10)
31/03/2021 01/01/2020 à 31/03/2020
4.01 Lucro Líquido do Período 44.168 9.204
4.03 Resultado Abrangente do Período 44.168 9.204
PÁGINA: 5 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Demonstração do Fluxo de Caixa - Método Indireto(cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Acumulado do Atual Acumulado do Exercício
Conta Exercício 01/01/2021 à Anterior(cid:13)(cid:10)
31/03/2021 01/01/2020 à 31/03/2020
6.01 Caixa Líquido Atividades Operacionais -35.366 20.947
6.01.01 Caixa Gerado nas Operações 150.686 107.357
6.01.01.01 Lucro Líquido do Exercício 44.168 9.204
6.01.01.02 Depreciação e Amortização 63.893 62.405
6.01.01.03 Ajuste a valor presente nos ativos e passivos 700 194
6.01.01.04 Juros sobre empréstimos, financiamentos e debêntures 8.614 11.091
6.01.01.05 Valor justo de instrumentos financeiros 1.091 -56.623
6.01.01.06 Variação Cambial 1.552 60.010
6.01.01.07 Juros sobre Arrendamento Mercantil 27.478 29.491
6.01.01.08 Constituição (reversão) da Provisão para Contingências 1.374 1.999
6.01.01.09 Resultado de equivalência patrimonial -371 553
6.01.01.10 Imposto de Renda e Contribuição Social Correntes 875 0
6.01.01.11 Imposto de Renda e Contribuição Social Diferidos 3.519 -15.163
6.01.01.13 Constituição (realização) das tarifas antecipadas - -1.751 156
empréstimos, financiamentos e debêntures
6.01.01.14 Outros ajustes ao lucro -112 -1.701
6.01.01.16 Provisão para encerramento de lojas -975 -572
6.01.01.17 Baixa líquida dos bens do ativo imobilizado e intangível 1.782 510
6.01.01.19 Provisão para perdas de crédito de liquidação duvidosa 1.895 1.667
6.01.01.20 Provisão para perdas nos estoques -3.046 4.136
6.01.02 Variações nos Ativos e Passivos -145.110 -44.796
6.01.02.01 Arrecadação de recursos de terceiros -4.002 527
6.01.02.02 Contas a Receber de Clientes -67.279 -20.746
6.01.02.04 Estoques -93.970 -29.502
6.01.02.05 Impostos a Recuperar 23.511 -20.057
6.01.02.06 Outros Créditos -24.789 8.804
6.01.02.07 Despesas antecipadas -13.322 -10.185
6.01.02.08 Fornecedores 5.391 11.705
6.01.02.09 Impostos e contribuições a recolher -1.265 -3.793
6.01.02.11 Salários e férias a pagar 25.766 10.064
6.01.02.13 Outras contas a pagar 4.849 8.387
6.01.03 Outros -40.942 -41.614
6.01.03.02 Pagamento de empréstimos tomados - juros -10.203 -5.705
6.01.03.03 Pagamento de debêntures tomada - juros -3.261 -6.418
6.01.03.05 Pagamento de arrendamentos - juros -27.478 -29.491
6.02 Caixa Líquido Atividades de Investimento 8.244 -5.172
6.02.05 Aplicações financeiras 30.850 -10
6.02.09 Aquisição de ativo imobilizado -19.596 -4.264
6.02.11 Aquisição de intangível -3.010 -898
6.03 Caixa Líquido Atividades de Financiamento -83.734 -54.397
6.03.01 Empréstimos tomados - Principal 160.000 0
6.03.02 Pagamento de empréstimos tomados - Principal -182.781 -28.106
6.03.03 Pagamento de Arrendamento Mercantil -32.666 -29.628
6.03.06 Pagamento de debênture tomada - principal -16.667 0
6.03.07 Liquidação dos swaps – efeito caixa 0 2.915
PÁGINA: 6 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Demonstração do Fluxo de Caixa - Método Indireto(cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Acumulado do Atual Acumulado do Exercício
Conta Exercício 01/01/2021 à Anterior(cid:13)(cid:10)
31/03/2021 01/01/2020 à 31/03/2020
6.03.09 Recursos provenientes das opções de ações outorgadas 0 422
6.03.12 Custos com Emissão de Ações -1.196 0
6.03.13 Ações em tesouraria -10.424 0
6.05 Aumento (Redução) de Caixa e Equivalentes -110.856 -38.622
6.05.01 Saldo Inicial de Caixa e Equivalentes 589.086 121.040
6.05.02 Saldo Final de Caixa e Equivalentes 478.230 82.418
PÁGINA: 7 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Demonstração das Mutações do Patrimônio Líquido / DMPL - 01/01/2021 à 31/03/2021(cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Capital Social Reservas de Capital, Reservas de Lucro Lucros ou Prejuízos Outros Resultados Patrimônio Líquido
Conta Integralizado Opções Outorgadas e Acumulados Abrangentes
Ações em Tesouraria
5.01 Saldos Iniciais 1.200.666 383.432 356.824 0 0 1.940.922
5.03 Saldos Iniciais Ajustados 1.200.666 383.432 356.824 0 0 1.940.922
5.04 Transações de Capital com os Sócios 0 -10.424 0 0 0 -10.424
5.04.04 Ações em Tesouraria Adquiridas 0 -10.424 0 0 0 -10.424
5.05 Resultado Abrangente Total 0 0 0 44.168 0 44.168
5.05.01 Lucro Líquido do Período 0 0 0 44.168 0 44.168
5.06 Mutações Internas do Patrimônio Líquido -1.196 2.734 0 0 0 1.538
5.06.08 Custos com Emissão de Ações -1.196 0 0 0 0 -1.196
5.06.09 Plano de Ações Restritas 0 2.734 0 0 0 2.734
5.07 Saldos Finais 1.199.470 375.742 356.824 44.168 0 1.976.204
PÁGINA: 8 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Demonstração das Mutações do Patrimônio Líquido / DMPL - 01/01/2020 à 31/03/2020(cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Capital Social Reservas de Capital, Reservas de Lucro Lucros ou Prejuízos Outros Resultados Patrimônio Líquido
Conta Integralizado Opções Outorgadas e Acumulados Abrangentes
Ações em Tesouraria
5.01 Saldos Iniciais 382.727 381.001 260.792 0 0 1.024.520
5.03 Saldos Iniciais Ajustados 382.727 381.001 260.792 0 0 1.024.520
5.05 Resultado Abrangente Total 0 0 0 9.204 0 9.204
5.05.01 Lucro Líquido do Período 0 0 0 9.204 0 9.204
5.06 Mutações Internas do Patrimônio Líquido 0 422 0 0 0 422
5.06.04 Opções Outorgadas Reconhecidas 0 422 0 0 0 422
5.07 Saldos Finais 382.727 381.423 260.792 9.204 0 1.034.146
PÁGINA: 9 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
DFs Individuais / Demonstração do Valor Adicionado (cid:13)(cid:10)
(cid:13)(cid:10)
(Reais Mil)
Código da Descrição da Conta Acumulado do Atual Acumulado do Exercício
Conta Exercício 01/01/2021 à Anterior(cid:13)(cid:10)
31/03/2021 01/01/2020 à 31/03/2020
7.01 Receitas 1.888.358 1.749.146
7.01.01 Vendas de Mercadorias, Produtos e Serviços 1.888.040 1.747.415
7.01.02 Outras Receitas 318 1.731
7.02 Insumos Adquiridos de Terceiros -1.292.671 -1.225.820
7.02.01 Custos Prods., Mercs. e Servs. Vendidos -1.115.121 -1.060.506
7.02.02 Materiais, Energia, Servs. de Terceiros e Outros -177.550 -165.314
7.03 Valor Adicionado Bruto 595.687 523.326
7.04 Retenções -63.893 -62.405
7.04.01 Depreciação, Amortização e Exaustão -63.893 -62.405
7.05 Valor Adicionado Líquido Produzido 531.794 460.921
7.06 Vlr Adicionado Recebido em Transferência 12.350 6.509
7.06.01 Resultado de Equivalência Patrimonial 371 -553
7.06.02 Receitas Financeiras 11.979 7.062
7.07 Valor Adicionado Total a Distribuir 544.144 467.430
7.08 Distribuição do Valor Adicionado 544.144 467.430
7.08.01 Pessoal 215.759 207.833
7.08.01.01 Remuneração Direta 182.382 173.774
7.08.01.02 Benefícios 20.055 21.436
7.08.01.03 F.G.T.S. 13.322 12.623
7.08.02 Impostos, Taxas e Contribuições 238.116 194.647
7.08.02.01 Federais 45.594 19.893
7.08.02.02 Estaduais 187.939 173.151
7.08.02.03 Municipais 4.583 1.603
7.08.03 Remuneração de Capitais de Terceiros 46.101 55.746
7.08.03.01 Juros 35.603 47.908
7.08.03.02 Aluguéis 10.498 7.838
7.08.04 Remuneração de Capitais Próprios 44.168 9.204
7.08.04.03 Lucros Retidos / Prejuízo do Período 44.168 9.204
PÁGINA: 10 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
Comentário do Desempenho
1T21
Fortaleza, Ceará, 3 de maio de 2021. A Empreendimentos Pague Menos S.A. (“Companhia” ou “Pague Menos”), desde 2009
única rede do varejo farmacêutico brasileiro presente em todos os estados do Brasil, levando saúde a mais de 300
municípiosbrasileiros,anunciaseus resultadosreferentes ao1°trimestre de2021.
As informações financeiras foram preparadas de acordo com as Normas Internacionais de Relatórios Financeiros (IFRS), de
acordo com as práticas contábeis adotadas no Brasil (BR GAAP) e foram revisadas pelos auditores independentes de acordo
com as normas brasileiras e internacionais de auditoria. Desde 2019, nossas demonstrações financeiras são preparadas de
acordo com o IFRS 16, que alterou os critérios de reconhecimento dos contratos de aluguel. Para demonstrar os efeitos da
implementação desta norma e facilitar a comparabilidade entre períodos, apresentamos na página 15 deste release o
DemonstrativodoResultadodoExercícioexcluindoosefeitosdoIFRS16.
PRINCIPAISDESTAQUES1T21
 Venda Mesmas Lojas: crescimento de 9,6% (8,7% em lojas maduras)
 Venda Média Loja Mensal: R$ 578 mil, crescimento de 10,6%
 Digital: crescimento de 140%, representando 6,1% das vendas totais (+3,4p.p. vs1T20)
 ClinicFarma: crescimento de 180% no faturamento, com adesão de 6,2% da base total de clientes
 EBITDA : R$ 159,3 milhões (+27,1% vs1T20), com margem EBITDA de 8,3% (+1,2p.p. vs1T20).
 Lucro Líquido :R$ 44,2 milhões (+380% vs1T20), com margem líquida de 2,3% (+1,8p.p. vs1T20)
 Mercado de Capitais: Valorização acumulada da ação desde o IPO de 12,9%
DESTAQUES FINANCEIROS (R$ milhões) 1T20 1T21 Δ
Receita Bruta 1.763,2 1.910,2 8,3%
Lucro Bruto 507,5 569,0 12,1%
% Margem Bruta 28,8% 29,8% 1,0 p.p.
Despesas com Vendas, Adm. e Gerais (382,1) (409,7) 7,2%
% Despesas (21,7%) (21,5%) 0,2 p.p.
EBITDA 125,4 159,3 27,1%
% Margem EBITDA 7,1% 8,3% 1,2 p.p.
Lucro (Prejuízo) Líquido 9,2 44,2 379,9%
% Margem Líquida 0,5% 2,3% 1,8 p.p.
DESTAQUES OPERACIONAIS 1T20 1T21 Δ
# de Lojas 1.124 1.101 (2,0%)
# de Lojas com Clinic Farma 801 823 2,7%
Venda Média/loja/mês (R$ mil) 523 578 10,6%
# de Atendimentos (mil) 29.536 26.067 (11,7%)
Ticket Médio (R$) 59,70 73,28 22,8%
# de Funcionários 19.900 19.121 (3,9%)
# de Funcionários/loja 17,7 17,4 (0,3)
% de Vendas dos Canais Digitais 2,7% 6,1% 3,4p.p.
PÁGINA: 11 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
Comentário do Desempenho
PORTFÓLIODELOJAS
Encerramoso1T21com1.101lojasdistribuídasem325municípios,sendo88,5%delojasmaduras.
Inauguramos em março de 2021 a primeira loja do novo ciclo de expansão, um mês antes da data planejada. O
cronograma de aberturas continua dentro do previsto, com mais lojas inauguradas no 2T21 e ritmo de aberturas
normalizadoduranteosegundosemestre.No1T21,foramfechadas5lojase7filiaisforamreformadas.
Base de Lojas Perfil Etário de Lojas
1º Ano 2º Ano 3º Ano Maduras
1.124 1.112 1.105 1.105 1.101
9,6%
1,8%
7,6%
1,1%
5,0%
0,8% 3,4%0,4%
9
0
,
,
7
1
%
%1,7%
10,6%
13,4%
12,8%
12,9%
85,6% 88,5%
75,7% 78,5% 80,8%
1T20 2T20 3T20 4T20 1T21 1T20 2T20 3T20 4T20 1T21
Distribuição por UF Aberturas de Lojas UDM*
RR: 9
AP: 6
Nordeste
CE: 180
PA: 34
AM: 22 RN: 43
MA: 60
PB: 51 100%
PI: 35
PE: 117
AC: 12
RO: 13 TO: 15 AL: 30
MT: 23 BA: 114 SE: 35 Fechamentos de Lojas UDM*
DF: 17
8%
Norte
GO: 28 MG: 63 4%
Nordeste 17%
MS: 23 ES: 26 Centro-Oeste
SP: 84
Sudeste 58% 13%
RJ: 19
Sul
PR: 15
SC: 20
RS: 7
* UDM: últimos doze meses
PÁGINA: 12 de 61
ITR - Informações Trimestrais - 31/03/2021 - EMPREENDIMENTOS PAGUE MENOS S.A. Versão : 1
Comentário do Desempenho
VENDAS
Atingimos no 1T21 receita bruta de R$ 1,9 bilhão, alta de 8,3% em relação ao 1T20, com crescimento mesmas lojas de
9,6% e lojas maduras de 8,7%. A venda média mensal por loja seguiu a tendência de crescimento observada nos
trimestresanterioresetotalizouR$578mil,crescimentode10,6%.Oníveldecrescimentoéaltosobretudoconsiderando
que a base de comparação do 1T20 foi impactada pela antecipação de compras relacionada ao desdobramento da
pandemiadeCovid-19emmarçode2020.
Receita Bruta Venda Média Loja/Mês
(em R$ milhões) (em R$ mil)
+8,3% +10,6%
1.955 590
1.902 1.910 574 578
1.763
1.688
523
506
1T20 2T20 3T20 4T20 1T21 1T20 2T20 3T20 4T20 1T21
Crescimento Total Crescimento Mesmas Lojas Crescimento Lojas Maduras
(variação %) (variação %) (variação %)
12,1% 14,0% 12,3%
8,8% 9,1% 8,3% 10,9% 11,0% 9,6% 8,4% 9,8% 8,7%
5,3%
3,3%
0,3%
1T20 2T20 3T20 4T20 1T21 1T20 2T20 3T20 4T20 1T21 1T20 2T20 3T20 4T20 1T21
O forte ritmo de crescimento é resultado da contínua melhoria de indicadores operacionais, canais e categorias de
produtos em relação ao 1T20, como: i) redução de 30% na ruptura de estoques; ii) incremento no sortimento de itens
vendidos em 5,5%; iii) aumento do NPS de clientes em 6 p.p., atingindo 73 pontos; iv) incremento de 3,4 p.p. na